# Generated by Django 2.1.7 on 2019-04-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_happy'),
    ]

    operations = [
        migrations.AddField(
            model_name='happy',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
    ]
