# Generated by Django 2.1.2 on 2019-04-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(null=True, on_delete=None, to='testapp01.Class'),
        ),
    ]
