# Generated by Django 2.1.2 on 2019-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtoG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='btog',
            name='b',
            field=models.ForeignKey(on_delete=None, to='webapp01.Man'),
        ),
        migrations.AddField(
            model_name='btog',
            name='g',
            field=models.ForeignKey(on_delete=None, to='webapp01.Woman'),
        ),
    ]
